controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # We need two separate controllers
    ezgripper_controller1:
      type: position_controllers/GripperActionController

    ezgripper_controller2:
      type: position_controllers/GripperActionController

# Config for Gripper 1 (Top)
ezgripper_controller1:
  ros__parameters:
    # Namespace is 'left_gripper1' based on the URDF macros
    joint: left_gripper1_ezgripper_knuckle_palm_L1_1
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 1.0
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

# Config for Gripper 2 (Bottom)
ezgripper_controller2:
  ros__parameters:
    # Namespace is 'left_gripper2' based on the URDF macros
    joint: left_gripper2_ezgripper_knuckle_palm_L1_1
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 1.0
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
