controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # The Main "Synced" Controller
    triple_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Configuration for the Synced Controller
triple_gripper_controller:
  ros__parameters:
    joints:
      - left_gripper1_ezgripper_knuckle_palm_L1_1
      - left_gripper2_ezgripper_knuckle_palm_L1_1
      - left_gripper3_ezgripper_knuckle_palm_L1_1
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
      
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
