# joint_limits.yaml
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  left_gripper1_ezgripper_knuckle_palm_L1_1:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true  # <--- MUST BE TRUE
    max_acceleration: 5.0          # <--- MUST BE > 0
  left_gripper2_ezgripper_knuckle_palm_L1_1:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_gripper3_ezgripper_knuckle_palm_L1_1:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 5.0
