# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    triple_gripper_controller_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

triple_gripper_controller:
  ros__parameters:
    joints:
      - left_gripper1_ezgripper_knuckle_palm_L1_1
      - left_gripper2_ezgripper_knuckle_palm_L1_1
      - left_gripper3_ezgripper_knuckle_palm_L1_1
    command_interfaces:
      []
    state_interfaces:
      []
    allow_nonzero_velocity_at_trajectory_end: true
